"""initial schema

Revision ID: 9780832d933e
Revises: 
Create Date: 2026-06-29 15:44:14.008928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9780832d933e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('season', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('stadiums',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('year_opened', sa.Integer(), nullable=True),
    sa.Column('history', sa.Text(), nullable=True),
    sa.Column('current_team', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('approved', 'pending_review', name='stadiumstatus'), nullable=False),
    sa.Column('submitted_by_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_leagues',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('league_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'league_id')
    )
    op.create_table('league_stadiums',
    sa.Column('league_id', sa.String(), nullable=False),
    sa.Column('stadium_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['stadium_id'], ['stadiums.id'], ),
    sa.PrimaryKeyConstraint('league_id', 'stadium_id')
    )
    op.create_table('teams',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('stadium_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('years_at_stadium', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['stadium_id'], ['stadiums.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visits',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('stadium_id', sa.String(), nullable=False),
    sa.Column('visit_type', sa.Enum('matchday', 'tour', name='visittype'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('match_home_team', sa.String(), nullable=True),
    sa.Column('match_away_team', sa.String(), nullable=True),
    sa.Column('match_competition', sa.String(), nullable=True),
    sa.Column('match_score', sa.String(), nullable=True),
    sa.Column('tour_overall_impression', sa.Enum('muy_bueno', 'bueno', 'normal', 'malo', name='tourimpression'), nullable=True),
    sa.Column('tour_highlights', sa.Text(), nullable=True),
    sa.Column('tour_would_recommend', sa.Boolean(), nullable=True),
    sa.Column('tour_guide_quality', sa.Enum('excelente', 'bueno', 'regular', 'sin_guia', name='tourguidequality'), nullable=True),
    sa.Column('tour_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['stadium_id'], ['stadiums.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visits')
    op.drop_table('teams')
    op.drop_table('league_stadiums')
    op.drop_table('user_leagues')
    op.drop_table('stadiums')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('leagues')
    # ### end Alembic commands ###
